import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:hive/hive.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'package:totelxapp/blocs/timer_cubit/timer_cubit.dart';
import 'package:totelxapp/models/user.dart';
import 'screens/login_screen.dart';
import 'blocs/user_cubit.dart';

void main() async {
  // 1. Ensure Flutter is initialized
  WidgetsFlutterBinding.ensureInitialized();

  // 2. Initialize Hive
  await Hive.initFlutter();

  // 3. Register the Adapter (The one generated by build_runner)
  Hive.registerAdapter(UserAdapter());

  // 4. Open the box BEFORE running the app
  await Hive.openBox<User>('users');
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MultiBlocProvider(
      providers: [
        BlocProvider(create: (_) => UserCubit()),
        BlocProvider(create: (_) => TimerBloc()),
      ],
      child: MaterialApp(
        debugShowCheckedModeBanner: false,
        title: 'Machine Test',
        theme: ThemeData(textTheme: GoogleFonts.montserratTextTheme()),
        home: LoginScreen(),
      ),
    );
  }
}
